# Generated by Django 4.2.16 on 2026-05-23 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_duration', models.PositiveIntegerField(help_text='Total duration in minutes')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed / Подтверждено'), ('cancelled', 'Cancelled / Отменено'), ('completed', 'Completed / Завершено'), ('rescheduled', 'Rescheduled / Перенесено')], db_index=True, default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='barbers.barberprofile')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
