# Generated by Django 4.2.16 on 2026-07-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('program', models.CharField(choices=[('little-barber', 'Little Barber'), ('barber', 'Barber'), ('top-barber', 'Top Barber'), ('undecided', 'Not decided yet')], default='undecided', max_length=30)),
                ('message', models.TextField(blank=True, help_text='What the applicant told us')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes, not shown to the applicant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academy Application',
                'verbose_name_plural': 'Academy Applications',
                'db_table': 'academy_applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='academy_app_status_f8f2e1_idx')],
            },
        ),
    ]
