# Generated by Django 4.2.16 on 2026-05-23 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyschedule',
            unique_together={('barber', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduleoverride',
            unique_together={('barber', 'date')},
        ),
    ]
