# Generated by Django 4.2.16 on 2026-07-29 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='category',
            field=models.CharField(choices=[('barber', 'Barber'), ('pro', 'Pro Barber'), ('top', 'Top Barber'), ('brend', 'Brend Barber')], db_index=True, default='barber', max_length=20),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price in somoni — used when no category price is set', max_digits=10),
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('barber', 'Barber'), ('pro', 'Pro Barber'), ('top', 'Top Barber'), ('brend', 'Brend Barber')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_prices', to='barbers.service')),
            ],
            options={
                'verbose_name': 'Service Price',
                'verbose_name_plural': 'Service Prices',
                'db_table': 'service_prices',
                'unique_together': {('service', 'category')},
            },
        ),
    ]
